// 주요 암호화폐의 한글 이름 매핑
export const COIN_NAMES: Record<string, string> = {
  BTC: '비트코인',
  ETH: '이더리움',
  BNB: '바이낸스 코인',
  ADA: '에이다',
  SOL: '솔라나',
  DOT: '폴카닷',
  DOGE: '도지코인',
  AVAX: '아발란체',
  MATIC: '폴리곤',
  LINK: '체인링크',
  UNI: '유니스왑',
  LTC: '라이트코인',
  BCH: '비트코인 캐시',
  XRP: '리플',
  ATOM: '코스모스',
  NEAR: '니어 프로토콜',
  FTM: '팬텀',
  ALGO: '알고랜드',
  VET: '비체인',
  ICP: '인터넷 컴퓨터',
  FIL: '파일코인',
  TRX: '트론',
  ETC: '이더리움 클래식',
  XLM: '스텔라',
  HBAR: '헤데라',
  THETA: '세타',
  XTZ: '테조스',
  AXS: '엑시 인피니티',
  SAND: '샌드박스',
  MANA: '디센트럴랜드',
  GALA: '갈라',
  CHZ: '칠리즈',
  ENJ: '엔진',
  HOT: '홀로체인',
  BAT: '브레이브',
  ZIL: '질리카',
  ONE: '하모니',
  IOTA: '아이오타',
  NEO: '네오',
  QTUM: '퀀텀',
  ZEC: '지캐시',
  DASH: '대시',
  XMR: '모네로',
  WAVES: '웨이브',
  RVN: '레이븐코인',
  CAKE: '팬케이크왑',
  SUSHI: '스시스왑',
  AAVE: '에이브',
  COMP: '컴파운드',
  MKR: '메이커다오',
  YFI: '연파이낸스',
  SNX: '신세틱스',
  CRV: '커브',
  '1INCH': '1인치',
  GRT: '그래프',
  ANKR: '앵커',
  STORJ: '스토리지',
  OCEAN: '오션 프로토콜',
  ALPHA: '알파 파이낸스',
  AUDIO: '오디우스',
  BAND: '밴드 프로토콜',
  CTSI: '카르테시',
  DYDX: '디와이디엑스',
  EGLD: '멀티버스엑스',
  FLOW: '플로우',
  HIVE: '하이브',
  ICX: '아이콘',
  IOTX: '아이오텍스',
  KAVA: '카바',
  KSM: '쿠사마',
  LRC: '루프링',
  NULS: '널스',
  OMG: '오미세고',
  ONT: '온톨로지',
  PROM: '프로메테우스',
  QNT: '퀀트',
  REN: '렌',
  RSR: '리저브라이트',
  SKL: '스케일',
  SRM: '세럼',
  STMX: '스톰엑스',
  SXP: '솔라',
  TFUEL: '세타 퓨엘',
  TOMO: '토모체인',
  TRB: '텔러',
  TROY: '트로이',
  VTHO: '베토르',
  WRX: '렉스',
  ZRX: '제로엑스',
  FET: '페치',
  AGIX: '싱귤래리티',
  RNDR: '렌더',
};

// 코인 카테고리 분류
export const COIN_CATEGORIES = {
  Major: ['BTC', 'ETH', 'BNB', 'ADA', 'SOL', 'DOT', 'DOGE', 'AVAX', 'MATIC'],
  DeFi: ['UNI', 'AAVE', 'COMP', 'MKR', 'YFI', 'SNX', 'CRV', '1INCH', 'SUSHI', 'CAKE'],
  Gaming: ['AXS', 'SAND', 'MANA', 'GALA', 'ENJ', 'CHZ'],
  AI: ['FET', 'OCEAN', 'AGIX', 'RNDR', 'GRT', 'BAND'],
  Metaverse: ['SAND', 'MANA', 'AXS', 'GALA', 'ENJ', 'CHZ'],
};

// 코인 카테고리 판별 함수
export function getCoinCategory(symbol: string): string {
  const baseAsset = symbol.replace('USDT', '');

  for (const [category, coins] of Object.entries(COIN_CATEGORIES)) {
    if (coins.includes(baseAsset)) {
      return category;
    }
  }

  return 'Other';
}